### ISSUE TITLE
支持websocket协议吗

### ISSUE THREAD

**Issue by xcly01** [zhkl0228/libnetguard#2]

**Comment by zhkl0228** [comment]
搜索项目的web socket关键词

**Comment by xcly01** [comment]
跑起来之后panic了，报错如下：
libnetguard-master % java -jar ./target/netguard-0.0.1-jar-with-dependencies.jar
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
VM option: -javaagent:/Users/ly/Downloads/libnetguard-master/target/netguard-0.0.1-jar-with-dependencies.jar=/Users/ly/Downloads/libnetguard-master/target/pre_master_secrets.log
java -jar ~/Downloads/libnetguard-master/target/netguard-0.0.1-jar-with-dependencies.jar 26217 ~/Downloads/libnetguard-master/target/pre_master_secrets.log
Exception in thread "main" java.lang.IllegalStateException: load RootCert failed.
	at com.github.netguard.vpn.ssl.RootCert.load(RootCert.java:47)
	at com.github.netguard.VpnServer.<init>(VpnServer.java:41)
	at com.github.netguard.VpnServer.<init>(VpnServer.java:44)
	at com.github.netguard.Main.main(Main.java:38)
Caused by: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at org.bouncycastle.jcajce.provider.keystore.util.AdaptingKeyStoreSpi.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.github.netguard.vpn.ssl.RootCert.load(RootCert.java:37)
	... 3 more

**Comment by zhkl0228** [comment]
没测试过打包运行，目前项目处于开发测试阶段

**Comment by xcly01** [comment]
能交流下么？怎么联系你呢？

**Comment by zhkl0228** [comment]
平时上社交比较少，有事可以发邮件给我
